---
# ihs-proxy/handlers/main.yml

- name: Restart ihs
  ansible.builtin.shell: |
    set -e
    {{ ihs_home }}/bin/apachectl stop
    sleep 1
    {{ ihs_home }}/bin/apachectl start
  become: true
  become_user: "{{ was_user }}"
  changed_when: true

- name: Reload ihs
  ansible.builtin.command:
    cmd: "{{ ihs_home }}/bin/apachectl restart"
  become: true
  become_user: "{{ was_user }}"
  changed_when: true
