apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: nexusliberty-app
  namespace: liberty-apps
  labels:
    app.kubernetes.io/name: nexusliberty-app
    app.kubernetes.io/component: backend
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server
  applicationImage: ghcr.io/jconover/nexusliberty-app:sha-9f301353c0a84b9343af46495b1557214959e2b1
  replicas: 2
  serviceAccountName: nexusliberty-sa
  pullPolicy: IfNotPresent
  expose: true
  route:
    termination: edge
  service:
    port: 9080
    type: ClusterIP
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: nexusliberty-app
            topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  readinessProbe:
    httpGet:
      path: /health/ready
      port: 9080
    initialDelaySeconds: 30
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /health/live
      port: 9080
    initialDelaySeconds: 60
    periodSeconds: 30
  startupProbe:
    httpGet:
      path: /health/live
      port: 9080
    failureThreshold: 30
    periodSeconds: 10
  env:
    - name: WLP_LOGGING_CONSOLE_FORMAT
      value: json
    - name: WLP_LOGGING_CONSOLE_LOGLEVEL
      value: info
