---
galaxy_info:
  role_name: was_deploy
  author: jconover
  description: WAS ND application deployment via wsadmin
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "9"

dependencies: []
