---
# was-base/handlers/main.yml

- name: Display was version
  ansible.builtin.command:
    cmd: "{{ was_home }}/bin/versionInfo.sh"
  become: true
  become_user: "{{ was_user }}"
  register: version_output
  changed_when: false
  listen: Display was version

- name: Show version output
  ansible.builtin.debug:
    msg: "{{ version_output.stdout_lines }}"
  listen: Display was version
